name:                ecicoin
version:             0.1.0.0
github:              "juanfrank7/ecicoin"
license:             BSD3
author:              "Juan F Gonzalez"
maintainer:          "juano_gonza@hotmail.com"
copyright:           "2019 Juan F Gonzalez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juanfrank7/ecicoin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ecicoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecicoin

tests:
  ecicoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ecicoin
